import Footer from "@/components/primitives/Footer";
import Navigation from "@/components/primitives/Navigation";
import { AuthProvider, ThemeProvider } from "@/components/primitives/Provider";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// to be typed as RootLayoutProps
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <AuthProvider>
          <body>
            <ThemeProvider attribute="class" defaultTheme="dark">
              <main className="flex h-full min-h-screen w-full flex-col relative">
                <Navigation />
                {children}
                <Footer />
              </main>
            </ThemeProvider>
            <Toaster />
          </body>
        </AuthProvider>
      </html>
    </>
  );
}
